services:
  - type: web
    name: nairobi-location-intelligence
    runtime: docker
    plan: free
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: nairobi-location-intelligence-db
          property: connectionString

databases:
  - name: nairobi-location-intelligence-db
    plan: free
    databaseName: nairobi_location_intelligence
    user: nairobi_location_intelligence
