MAJOR_CATEGORY_MAP = {
    'restaurant': 'Food & Drink',
    'cafe': 'Food & Drink',
    'bar': 'Food & Drink',
    'pub': 'Food & Drink',
    'fast_food': 'Food & Drink',
    'nightclub': 'Food & Drink',

    'clinic': 'Health',
    'hospital': 'Health',
    'pharmacy': 'Health',
    'doctors': 'Health',
    'dentist': 'Health',
    'chemist': 'Health',
    'social_facility': 'Health',

    'school': 'Education',
    'college': 'Education',
    'university': 'Education',
    'kindergarten': 'Education',
    'library': 'Education',
    'educational_institution': 'Education',
    'childcare': 'Education',
    'dormitory': 'Education',

    'bank': 'Finance',
    'atm': 'Finance',
    'bureau_de_change': 'Finance',
    'insurance': 'Finance',

    'fuel': 'Transport',
    'bus_station': 'Transport',
    'bus_stop': 'Transport',
    'parking': 'Transport',
    'taxi': 'Transport',
    'car_wash': 'Transport',
    'car_repair': 'Transport',
    'garage': 'Transport',
    'motorway_junction': 'Transport',
    'stop_position': 'Transport',
    'parking_space': 'Transport',
    'parking_entrance': 'Transport',
    'bicycle_parking': 'Transport',
    'motorway': 'Transport',
    'motorway_link': 'Transport',
    'tertiary_link': 'Transport',
    'rail': 'Transport',
    'station': 'Transport',
    'platform': 'Transport',
    'service': 'Transport',
    'secondary': 'Transport',
    'tertiary': 'Transport',
    'primary': 'Transport',
    'trunk': 'Transport',
    'secondary_link': 'Transport',
    'primary_link': 'Transport',
    'trunk_link': 'Transport',
    'footway': 'Transport',
    'path': 'Transport',
    'living_street': 'Transport',
    'track': 'Transport',

    'mall': 'Shopping',
    'marketplace': 'Shopping',
    'retail': 'Shopping',
    'commercial': 'Shopping',
    'supermarket': 'Shopping',
    'convenience': 'Shopping',
    'kiosk': 'Shopping',
    'butcher': 'Shopping',
    'hairdresser': 'Shopping',
    'electronics': 'Shopping',
    'clothes': 'Shopping',
    'alcohol': 'Shopping',
    'general': 'Shopping',
    'hardware': 'Shopping',
    'furniture': 'Shopping',
    'greengrocer': 'Shopping',
    'computer': 'Shopping',
    'beauty': 'Shopping',
    'shoes': 'Shopping',
    'car': 'Shopping',
    'travel_agency': 'Shopping',
    'mobile_money_agent': 'Finance',
    'money_transfer': 'Finance',

    'place_of_worship': 'Religion',
    'church': 'Religion',
    'mosque': 'Religion',

    'police': 'Government',
    'fire_station': 'Government',
    'courthouse': 'Government',
    'townhall': 'Government',
    'government': 'Government',
    'public_building': 'Government',
    'post_office': 'Government',
    'diplomatic': 'Government',
    'surveillance': 'Government',
    'lawyer': 'Government',
    'prison': 'Government',
    'political_party': 'Government',

    'drinking_water': 'Water & Sanitation',
    'water_point': 'Water & Sanitation',
    'toilets': 'Water & Sanitation',
    'waste_disposal': 'Water & Sanitation',
    'waste_transfer_station': 'Water & Sanitation',
    'waste_basket': 'Water & Sanitation',
    'recycling': 'Water & Sanitation',
    'water_tap': 'Water & Sanitation',
    'water_tower': 'Water & Sanitation',
    'storage_tank': 'Water & Sanitation',

    'hotel': 'Accommodation',
    'guest_house': 'Accommodation',
    'hostel': 'Accommodation',
    'motel': 'Accommodation',
    'apartments': 'Accommodation',
    'apartment': 'Accommodation',
    'residential': 'Accommodation',

    'museum': 'Entertainment',
    'attraction': 'Entertainment',
    'park': 'Entertainment',
    'sports_centre': 'Entertainment',
    'pitch': 'Entertainment',
    'cinema': 'Entertainment',
    'theatre': 'Entertainment',
    'arts_centre': 'Entertainment',
    'playground': 'Entertainment',
    'garden': 'Entertainment',
    'swimming_pool': 'Entertainment',
    'fitness_centre': 'Entertainment',
    'casino': 'Entertainment',
    'picnic_site': 'Entertainment',
    'monument': 'Entertainment',
    'stadium': 'Entertainment',
    'artwork': 'Entertainment',
    'fountain': 'Entertainment',
    'zoo': 'Entertainment',
    'viewpoint': 'Entertainment',
    'golf_course': 'Entertainment',
    'gallery': 'Entertainment',
    'events_venue': 'Entertainment',

    'community_centre': 'Public Services',
    'ngo': 'Public Services',
    'information': 'Public Services',
    'shelter': 'Public Services',
    'public': 'Public Services',
    'association': 'Public Services',
    'research': 'Public Services',
    'telecommunication': 'Public Services',

    'internet_cafe': 'Food & Drink',
    'food_court': 'Food & Drink',
    'ice_cream': 'Food & Drink',
}


def major_category_for(category, current_major='Other'):
    """Return a normalized major category for a raw POI category."""
    category_key = str(category or '').strip().lower()
    if category_key in MAJOR_CATEGORY_MAP:
        return MAJOR_CATEGORY_MAP[category_key]
    if current_major and current_major != 'Other':
        return current_major
    return 'Other'
