# Generated by Django 4.2.7 on 2026-05-09 09:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_key', models.CharField(max_length=100, unique=True)),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('major_category', models.CharField(max_length=100)),
                ('ward_name', models.CharField(max_length=100)),
                ('ward_key', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='location_intelligence.ward')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['major_category'], name='location_in_major_c_b580b7_idx'), models.Index(fields=['category'], name='location_in_categor_9e9249_idx'), models.Index(fields=['ward_key'], name='location_in_ward_ke_e8eff3_idx'), models.Index(fields=['name'], name='location_in_name_581e34_idx')],
            },
        ),
    ]
