# Generated by Django 4.2.7 on 2026-05-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='data_source',
            field=models.CharField(choices=[('osm', 'OpenStreetMap'), ('local', 'Local backup')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='pointofinterest',
            name='external_source_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['data_source'], name='location_in_data_so_2226e4_idx'),
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['external_source_id'], name='location_in_externa_fa6c5e_idx'),
        ),
    ]
