# Generated by Django 4.2.7 on 2026-05-09 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location_intelligence', '0002_pointofinterest_data_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='inside_nairobi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='pointofinterest',
            index=models.Index(fields=['inside_nairobi'], name='location_in_inside__c71eb6_idx'),
        ),
    ]
